# From scratch

In [34]:
import numpy as np
import random
# Data 
data = np.array([13,8,25,8,2,30,5,4,35,9])
data

array([13,  8, 25,  8,  2, 30,  5,  4, 35,  9])

In [35]:
# choose 3  points as initial centroids
k = 3
medoids = data[random.sample(range(len(data)), k)]
medoids

array([35,  5, 13])

In [36]:
def distance(a, b):
    return abs(a - b)

In [37]:
def total_cost(data, medoids):
    total = 0
    for point in data:
        dists = [distance(point, m) for m in medoids]
        total += min(dists)
    return total

In [38]:
previous_cost = float('inf')

for i in range(10): 
    clusters = [[],[],[]]
    for point in data:
        dists = [distance(point, m) for m in medoids]
        cluster_index = np.argmin(dists)
        clusters[cluster_index].append(point)
    
    new_medoids = []
    for cluster in clusters:
        costs = [sum(distance(p,c) for c in cluster) for p in cluster]
        new_medoids.append(cluster[np.argmin(costs)])
    new_medoids = np.array(new_medoids)
    
    current_cost = total_cost(data, new_medoids)
    if current_cost >= previous_cost:
        print("Stop")
        break
    previous_cost = current_cost
    medoids = new_medoids


print(medoids)
print(clusters[0])
print(clusters[1])
print(clusters[2])

Stop
[30  8 13]
[25, 30, 35]
[8, 8, 2, 5, 4, 9]
[13]
